# Generated by Django 5.2.8 on 2025-11-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_course_created_at_alter_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_at',
            new_name='created_by',
        ),
    ]
